title: Mein Jupyter Book Test
author: Data Train Team
only_build_toc_files: true

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      use_repository_button: true
      repository_url: https://github.com/DataTrainUBRA/DigitalToolkitTest
      repository_branch: main
      path_to_docs: book-src
